### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by dominhhai** [tiepvupsu/tiepvupsu.github.io#2]
Hi!
Thanks for your awesome work.
Can you enable HTTPS protocol for your site?

**Comment by tiepvupsu** [comment]
Hi,

Thank you for your words. 

I tried to enable https but the domain I'm using now doesn't have that option (it provides https but not compatible with github).

**Comment by dominhhai** [comment]
These links are about CloudFlare, the similar steps is useful, IMO.

1. https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc
2. https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html

**Comment by tiepvupsu** [comment]
Thank you,

I tried these but didn't succeed. I'll try them one more time later.

**Comment by dominhhai** [comment]
Sorry for this annoy request!
Wait for your support.

**Comment by tiepvupsu** [comment]
No problem at all. 

I knew that many readers feel unsafe with http, but no worries. Since this site is a static web without requiring any account/password, none of your information will be stolen. 

Btw, I tried the CloudFlare again but couldn't figure out the problem.

**Comment by dominhhai** [comment]
Seem that your SSL Certification has problems.
Your site can be connected with https, however Chrome show that your site is not secure.
Your SSL certification may be signed invalid or expired.  

![mlb](https://user-images.githubusercontent.com/1484298/26856621-cad1e9a4-4b5f-11e7-8eaf-ac661513f41e.png)

**Comment by tiepvupsu** [comment]
As I said, this is fine. Chrome and other browsers consider any http site as insecure. That's true for sites which keep users' information. For this blog, this is ok since as I said, it's static and doesn't require any of your info. 

So, you're safe here. 

I'll try enable https if I have time, not in near future. Thank you for your consideration.

**Comment by dominhhai** [comment]
Sorry for all. I will close is issue.
