### ISSUE TITLE
vcs file not able to pull due to conflict naming convention

### ISSUE THREAD

**Issue by matrix3dim** [tiepvupsu/tiepvupsu.github.io#4]
Hello bạn Tiệp,

First of all thank you so much for your blog and code sharing for newbie ML like me.
It is very useful to start.
I have tried to checkout your source code but it got problem to check out the cvs file tiepvu-2017-03-04T03:18:40.438849-links.csv due to conflict naming convention on Window.

Could you consider to change the file name so that it works in all dev platform?
Or do you have solution for this issue?

Best Regards,
Hoàng Tăng Hóa

**Comment by machinelearningcoban** [comment]
Hi Hoá,

Could you please tell me which lesson you are talking about? I've never seen this filename before. 

Thanks,
Tiệp

**Comment by matrix3dim** [comment]
Hi Tiệp,

I download this: https://github.com/tiepvupsu/tiepvupsu.github.io/issues/4

**Comment by matrix3dim** [comment]
Hi Tiệp,

I download this: https://github.com/tiepvupsu/tiepvupsu.github.io
But seem to this is web page source code for your blog, not ML, isn't it?

I am reading and practicing this topic: http://machinelearningcoban.com/2016/12/28/linearregression/ 

Regards,
Hoa.

**Comment by machinelearningcoban** [comment]
Hi there,

That file is not important at all. It doesn't relate to any part of ML code. I deleted it actually. 

Tiep

**Comment by matrix3dim** [comment]
Oh, thanks !!

**Comment by machinelearningcoban** [comment]
No problem. 

If your concern is addressed, please close the issue. 

Thank you.
