### ISSUE TITLE
 ví dụ với user có id là 100

### ISSUE THREAD

**Issue by giangm9** [tiepvupsu/tiepvupsu.github.io#8]
Trong ví dụ với user có id là 100. tác giả truyền 10 vào hàm số get_items_rated_by_user:
ids, scores = get_items_rated_by_user(rate_test, 10)
==> tại sao lại truyền 10 vào hàm số này ? mà không phải là:
ids, scores = get_items_rated_by_user(rate_test, 100)

**Comment by tiepvupsu** [comment]
Cảm ơn bạn. Chỗ đó mình nhầm một chút. Phải là user id = 10. Mình đã sửa lại.
